### ISSUE TITLE
Improvement to the way .fortify strips variable names from the strata labels

### ISSUE THREAD

**Issue by peterdutey** [ellessenne/KMunicate-package#12]
Hi there,
I would like to suggest a very minor improvement (see commit in forked repository e7dd8b1173eea2909202eb4c8c261ed5b7afcef7)
At present if a strata variable has levels containing equal signs, .fortify() will strip all characters before the *last* equal sign in the label. This is because the regular expression is 'greedy', and because of using gsub() instead of sub().
This results in labels in both the legend and the risk table being truncated.
Please refer to my forked repository for correction and unit tests.
Hope this makes sense and is easy to contribute!
Thanks
Peter 

```
library(KMunicate)
data("cancer2", package = "KMunicate")
# Create typical strata labels presenting thresholds in a biomarker
cancer2$biomarker1 <- factor(
  ifelse(cancer2$drug==1, 1, 2), 
  labels = c("Biomarker <= 5", "Biomarker > 5")
)
# Stripping anything before an equal sign
levels(KMunicate:::.fortify(survfit(Surv(studytime, died) ~ biomarker1, data = cancer2))$strata)
[1] " 5"            "Biomarker > 5"
# The legend and risk tables therefore display truncated labels
KMunicate(
  fit = survfit(Surv(studytime, died) ~ biomarker1, data = cancer2), 
  time_scale = seq(0, max(cancer2$studytime), by = 7)
)
```

![Rplot01](https://github.com/ellessenne/KMunicate-package/assets/46346161/42f56a10-f98b-4c54-98a3-e9f131ef10dc)

**Comment by ellessenne** [comment]
Hi @peterdutey, thanks for reporting this – looks like something that should definitely be addressed, would you mind creating a PR with your patch? Thanks!

Alessandro
