### ISSUE TITLE
Subjects at risk

### ISSUE THREAD

**Issue by anddis** [ellessenne/KMunicate-package#5]
Hi Alessandro,
Thank you for a great and useful R package!

I'm just a little confused by the `cancer` data example and, in particular, by the "at risk" figures in the risktable (the dataset is small enough to notice when weird stuff happens).
For example, the largest event time for `drug = 1`is 23. How can 2 subjects be still at risk at day 28? Likewise for `drug = 2`.
Or, how can 20 subjects be at risk at time 7 in `drug = 1`?
Well, you get the idea :)

Thanks again and keep it up!

**Comment by ellessenne** [comment]
Hi Andrea,
Thanks for the feedback, that was something that I wanted to double-check indeed — I think I got it the other way around with the internal calculations, the way it is right now corresponds to _how many people were at risk *before* a given time_, or in other words, in the previous interval, which is obviously not what it's supposed to be! I'll get this fixed :)

**Comment by ellessenne** [comment]
Hi again,
I updated the calculations (which now is using `summary.survfit` from the {survival} package: I think now it's better (see below)!


![5](https://user-images.githubusercontent.com/10330005/87219879-4d098380-c35f-11ea-8d8b-53f3f6149c8f.png)

**Comment by anddis** [comment]
Amazing! Thank you, Alessandro 🙏🏻
...and the graph you put on the landing page is even better than this one: it shows the risk table for drug 1 and 2 at times 28 and 35 as well!

**Comment by ellessenne** [comment]
Thanks Andrea! It turns out, everything was already implemented in the {survival} package, I only had to extract the right data from a `summary.survfit` obkect!
