### ISSUE TITLE
using KMunicate style KM in jamovi

### ISSUE THREAD

**Issue by sbalci** [ellessenne/KMunicate-package#7]
Dear @ellessenne 

I am developing modules for [jamovi.org](jamovi.org). Some examples are here: [https://sbalci.github.io/ClinicoPathJamoviModule/](https://sbalci.github.io/ClinicoPathJamoviModule/)

I really liked this approach of KM curves. And I have implemented it to the [jsurvival module for jamovi](https://github.com/sbalci/jsurvival). I think it will be very useful for pathologists and clinicians.

Below is the output.

<img width="1259" alt="jamovi-KMunicate" src="https://user-images.githubusercontent.com/7208830/90027102-d4c91180-dcc0-11ea-9509-35c3c8d9f80c.png">

Please let me know your comments and suggestions.

Serdar Balci

**Comment by ellessenne** [comment]
Hi @sbalci, cool that you included KMunicate-style plots in jamovi.
I am not really the target audience (:wink:) so I wouldn't know what to comment really, but impressive work!

**Comment by sbalci** [comment]
Thank you very much :)
